### ISSUE TITLE
Split the content of packages?

### ISSUE THREAD

**Issue by dvidsilva** [bower/components#1]
Right now packages has over 50k entries, github truncates the view and it can be hard to navigate. Would it help to split the content of that folder into individual folders? like A-Z or even more? and then put the packages on the folder that matches their first letters?

Looks like given the way the registry works this wouldn't be super compatible? just wondering.

**Comment by benmann** [comment]
Yep, I think the only (and important) thing preventing this is that older Bower versions use `/packages/<name>` as the registry endpoint. Therefore if we moved the packages into sub-folders, we'd lose backwards compatibility. If we keep it like it is, you should be able to just point to this repo.

I also dunno if there are many cases in which one wants to navigate the repo, as we have migrations for changes. However if you really have to, you could also use GitHub's search, which pretty neat when you know what you're looking for: https://github.com/bower/components/find/master 😉

**Comment by sheerun** [comment]
Yes, exactly. The structure represents what current Bower versions expect when fetching from registry. We cannot namespace files by anything, or append .json to files
