### ISSUE TITLE
List all packages

### ISSUE THREAD

**Issue by anvaka** [bower/components#7]
Hello!

I'm trying to update [visualization of bower](http://anvaka.github.io/pm/#/galaxy/bower?cx=0&cy=0&cz=0&lx=0.0000&ly=0.0000&lz=0.0000&lw=1.0000&ml=150&s=1.75&l=1&v=2015-12-12T20-00-00Z). Previously I used https://bower-component-list.herokuapp.com/ to fetch list of all packages. This host is no longer working.

What is the most accurate way to get up to date versions of packages?

**Comment by sheerun** [comment]
It's https://bower.herokuapp.com/packages
